Add AlpsItemEdit json schema
ma-alps/spec pull request #43
Opened 2021-06-11 07:53 UTC by poemn

Fix #8

2021-06-11 08:04 UTC, acio-o9 commented on schema/AlpsItemEdit.json
> +    "AlpsItem": {
`alpsItem` ですかね？

2021-06-11 08:08 UTC, NaokiTsuchiya requested changes

2021-06-11 08:08 UTC, NaokiTsuchiya commented on schema/AlpsItemEdit.json
> +    "AlpsItem": {
`alpsItem` ?

2021-06-11 08:08 UTC, poemn commented on schema/AlpsItemEdit.json
> +    "AlpsItem": {
それでした！笑

2021-06-11 08:09 UTC, poemn commented on schema/AlpsItemEdit.json
> +    "AlpsItem": {
🙈

2021-06-11 08:12 UTC, poemn commented on schema/AlpsItemEdit.json
> +    "AlpsItem": {
修正しました！

2021-06-11 08:12 UTC, poemn commented on schema/AlpsItemEdit.json
> +    "AlpsItem": {
修正しました！

2021-06-18 04:28 UTC, NaokiTsuchiya commented on schema/response/example/AlpsItemEdit.json
> +  }
alpsItemから消しちゃったんですが、リクエストには asdUrl とか profileUrl が必要なんですよね。💦

@koriym #36 で消しちゃいましたが、戻したほうがいいですかね。

2021-06-18 06:10 UTC, NaokiTsuchiya commented on schema/response/example/AlpsItemEdit.json
> +  }
- profileを治す。 `profileUrl` と `asdUrl` を  AlpsItemに追記

```xml
<descriptor id="AlpsItem">
<descriptor id="asdUrl" href="https://raw.githubusercontent.com/alps-io/imports/master/schema.org/types/URL.json" title="ASD のurl" />
<descriptor id="profileUrl" href="https://raw.githubusercontent.com/alps-io/imports/master/schema.org/types/URL.json" title="ALPS profile のurl" />
</descriptor>
```

2021-06-18 06:46 UTC, NaokiTsuchiya approved these changes

2021-06-18 06:49 UTC, merged